"""create items and stock_movements

Revision ID: 1f5e6e07b1f6
Revises: 
Create Date: 2026-08-14 22:17:50.170067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.types


# revision identifiers, used by Alembic.
revision: str = '1f5e6e07b1f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('reorder_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', app.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.types.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_items_quantity_non_negative'),
    sa.CheckConstraint('reorder_threshold >= 0', name='ck_items_reorder_threshold_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_sku'), ['sku'], unique=True)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.types.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('delta <> 0', name='ck_stock_movements_delta_non_zero'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_item_id'), ['item_id'], unique=False)
        batch_op.create_index('ix_stock_movements_item_id_id', ['item_id', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_movements_item_id_id')
        batch_op.drop_index(batch_op.f('ix_stock_movements_item_id'))

    op.drop_table('stock_movements')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_sku'))
        batch_op.drop_index(batch_op.f('ix_items_location'))

    op.drop_table('items')
    # ### end Alembic commands ###
